### Obtencion de todos los productos
### /productos

//Consulta "Mostrar todos los productos"
###GET http://localhost:1234/productos

//Consulta 1
###GET http://localhost:1234/usuarios

//Consulta 2
###GET http://localhost:1234/usuarios/1

//Consulta 3
###POST  http://localhost:1234/usuarios

//Consulta 4
###PUT http://localhost:1234/usuarios/1

//Consulta 5 
###DELETE http://localhost:1234/usuarios/1

//Consulta 6
###GET http://localhost:1234/productos/precio/1

//Consulta 7
###GET http://localhost:1234/productos/nombre/1

//Consulta 8
###GET http://localhost:1234/usuarios/telefono/1

//Consulta 9
###GET http://localhost:1234/usuarios/nombre/1

//Consulta 10
GET http://localhost:1234/productos/total-stock


